title: Karen Loscocco
logo: "/images/logo.jpeg?raw=true"
description: >
I am a self-motivated industrial engineering student seeking a full-time position requiring critical thinking and problem-solving ability. I am eager to put my knowledge and experience in data science and machine learning to practical use within a company that embraces creativity and innovation. 
<br><br>
<a href="https://www.linkedin.com/in/karen-loscocco">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
